# -*- coding: utf-8 -*-
"""P-110

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1jcLKG-9BP7KbpSVoxFTo49nz_FvpqPsB
"""

from google.colab import files
file_toload=files.upload()

import statistics
import plotly.figure_factory as ff
import pandas as pd
import csv
import random

df=pd.read_csv("data.csv")

data=df["temp"].tolist()

figure=ff.create_distplot([data],["temp"],show_hist=False)
figure.show()

std_deviation=statistics.stdev(data)
population_mean=statistics.mean(data)
print("Population mean:",population_mean)
print("Standard deviation:",std_deviation)

dataset=[]
for i in range(0,100):
  random_index=random.randint(0,len(data))
  value=data[random_index]
  dataset.append(value)
mean=statistics.mean(dataset)
std_deviation1=statistics.stdev(dataset)
print("Sample mean:",mean)
print("Standard deviation:",std_deviation1)

def random_set_of_mean(counter):
  dataset=[]
  for i in range(0,counter):
    random_index=random.randint(0,len(data)-1)
    value=data[random_index]
    dataset.append(value)
  mean=statistics.mean(dataset)
  std_deviation1=statistics.stdev(dataset)
  return mean

import plotly.graph_objects as go
def showfig(mean_list):
  df=mean_list
  mean=statistics.mean(mean_list)
  print("Mean of sampling distribution",mean)
  fig=ff.create_distplot([df],["temp"],show_hist=False)
  fig.add_trace(go.Scatter(x=[mean,mean],y=[0,1],mode="lines",name="MEAN"))
  fig.show()

def setup(): 
  mean_list = [] 
  for i in range(0,1000): 
    set_of_means= random_set_of_mean(100) 
    mean_list.append(set_of_means) 
  showfig(mean_list) 
  mean = statistics.mean(mean_list)
setup()

def standard_deviation():
  mean_list=[]
  for i in range(0,1000):
    set_of_means=random_set_of_mean(100)
    mean_list.append(set_of_means) 
  std_deviation2= statistics.stdev(mean_list)
  print("Standard deviation:",std_deviation2)
standard_deviation()